### PR TITLE
issue #152 bugfix

### PR DESCRIPTION
**Pull request by pkrolikowski**
Override default headers is now possible.

### CODE REVIEW

**Comment by Lukasa** [comment]
Hi @pkrolikowski! Thanks for proposing this change! I'm looking forward to working through it with you!

So I don't believe this is addressing the core issue correctly. The problem here specifically is that the way the CLI handles the headers does not allow for overriding the special headers (like `:authority`). This is not a problem in the `HTTP20Connection` class, which *does* allow it (and is where you've made a change). Instead, the problem is likely to be in the `cli.py` file somewhere.

Take a look at this suggested call to the CLI tool:

```
$ hyper --debug GET https://google.com:443/ :authority:google.ru
...
HPACK encoding [(':method', 'GET'), (':scheme', 'https'), (':authority', 'google.com'), (':path', '/'), ('', 'authority:google.ru')]
```

This suggests that the CLI tool is setting the header to `('', 'authority:google.ru')`. This is probably a parsing problem: we'd like to have a leading colon if possible.

**Comment by pkrolikowski** [comment]
OK, I'll look at cli.py. So the correct behave should be like this:

$ hyper --debug GET https://google.com:443/ :authority:google.ru
...
HPACK encoding [(':method', 'GET'), (':scheme', 'https'), (':authority', 'google.com'), (':path', '/'), (':', 'authority:google.ru')]

$ hyper --debug GET https://google.com:443/ authority:google.ru
...
HPACK encoding [(':method', 'GET'), (':scheme', 'https'), (':authority', 'google.ru'), (':path', '/')]

Am I right ?

**Comment by Lukasa** [comment]
No, I think the correct behaviour should be:

```
$ hyper --debug GET https://google.com:443/ :authority:google.ru
...
HPACK encoding [(':method', 'GET'), (':scheme', 'https'), (':authority', 'google.ru'), (':path', '/')]
```

**Comment by pkrolikowski** [comment]
I've changed the way how set_request_data() in cli.py is processing headers separation.

**Comment by Lukasa** [comment]
Thanks for this @pkrolikowski! That code looks plausible enough to me.

To verify that it works, can you please write some tests to see how it functions with a variety of inputs? (I apologise for the Travis problems, it seems that Travis has a timing issue with our disabling TLS certificate verification in the tests)

**Pull request closed without merging**
