### PR TITLE
Work around cryptography support in old PyPy

### LINKED ISSUE #161: PyPy builds are broken
See [this build](https://travis-ci.org/Lukasa/hyper/builds/77454850) for more.

### PR DESCRIPTION
**Pull request by Lukasa**
Fixes #161.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Word of caution: This will not work for wheels.

**Comment by Lukasa** [comment]
Yeah. =( Frankly, the `setup.py` in this module is being a little bit over-clever, but I'm not really confident that we can do anything else.

**Comment by sigmavirus24** [comment]
Specifically what I meant is the following:

If you build a wheel on CPython 2.7, the requirements will statically say "cryptography 1.0 is okay" and someone installing that wheel on PyPy < 2.6.0 will get that requirement and it will cause them to install 1.0 and for things to be broken.

I would be careful about publishing wheels at this point because of this.

**Comment by Lukasa** [comment]
Yeah, I got that.

What I mean is that the `setup.py` has a number of flaws exactly like that, because I publish universal wheels. This is altogether somewhat problematic.

**Comment by sigmavirus24** [comment]
Yeah, I would say you should stop publishing universal wheels because of this =(. pip 7.x.y will build wheels and cache them for you so they'll be 100% appropriate for each user.

**Pull request merged**
