### PR TITLE
Start of http11 upgrade test

### PR DESCRIPTION
**Pull request by fredthomsen**
Only started on the first test. I'll wrap it up this afternoon.

### CODE REVIEW

**Comment by fredthomsen** [comment]
The upgrade test fits nicely into `test/test_integration_http11.py`, but where is a good place for the standard plaintext HTTP2.0 test?

**Comment by Lukasa** [comment]
Given the changes you're making, I'd say it's going to be in test_integration.py (which is implicitly HTTP/2 focused).

**Comment by fredthomsen** [comment]
In that case should all those tests be run a second time with plaintext http or just treat the insecure case as a one-off test?

**Comment by Lukasa** [comment]
Goood question.

Ideally I'd like us to be able to do all the tests twice, once secure and once not. A py.test fixture should give us the power to do that. For now, though, let's do a one-off and take a work item to investigate having the tests do both secure and insecure work.

**Comment by fredthomsen** [comment]
Go ahead and look this over.  I think it's ready.

**Comment by Lukasa** [comment]
Alrighty this looks good to me. Thanks @fredthomsen!

I don't think there are any other dependencies on the integration tests, so they really shouldn't hang. I assume you installed all of test_requires.txt?

**Pull request merged**
