### PR TITLE
removing stream from recent_recv_streams on clean close

### PR DESCRIPTION
**Pull request by nateprewitt**
This addresses #265. Not sure if the test is overkill for such a minor change, but I figured I'd err on the side of 101% coverage :) I'll strip it out if it's unneeded.

### CODE REVIEW

**Comment by Lukasa** [comment]
Thanks for this!

I'm happy with the change, and have no objection to that test, but I'd also like a more specific test. Can we write a test that cleanly closes one stream? That is, that uses a stream through its lifetime, such that it gets a complete response, and then confirms that it has been removed from everything?

**Comment by nateprewitt** [comment]
Were you looking for something more along the lines of [this](https://github.com/nateprewitt/hyper/commit/624afca#diff-3f0c2e4380c8aaed128603ed40d5f22fR262)? This is what I originally wrote but felt it might exercise unnecessary code.

**Comment by Lukasa** [comment]
Yup @nateprewitt, that looks right.

**Comment by nateprewitt** [comment]
Replaced old test with lifecycle test. The former felt redundant with this one.

**Comment by Lukasa** [comment]
Fab, thanks @nateprewitt! :sparkles: :cake: :sparkles:

**Pull request merged**
